In [19]:
from numpy import random
#generate an array of 10 values that follow a binomial distribution
random.binomial(n=5, p=.25, size=10)


array([2, 1, 1, 0, 1, 0, 1, 2, 1, 3])

In [33]:
import numpy as np

def bern(p,size=1):
    rvs = np.array([])
    for i in range(0,size):
        if np.random.rand() <= p:
            a=1
            rvs = np.append(rvs,a)
        else:
            a=0
            rvs = np.append(rvs,a)
    return rvs

    #test example: Tossing a coin. generate the random variate 10 times to see how many head(1) and how many tail(0) occur.

bern(0.5, 10)

array([1., 0., 0., 1., 1., 1., 1., 0., 1., 0.])

In [34]:
import numpy as np

def bern(p,size=1):
    rvs = np.array([])
    for i in range(0,size):
        if np.random.rand() <= p:
            a=1
            rvs = np.append(rvs,a)
        else:
            a=0
            rvs = np.append(rvs,a)
    return rvs

#test example: Tossing a coin. generate the random variate 10 times to see how many head(1) and how many tail(0) occur.

bern(0.5, 10)

array([1., 0., 0., 0., 0., 1., 1., 0., 0., 1.])

In [32]:
# from numpy import random
# np.random.negative_binomial(n, p, size=None)

np.random.negative_binomial(n=1, p=0.1, size = 10)

array([ 7, 25, 14,  8, 10, 10,  0, 19,  5, 41])

In [22]:
from numpy import random
# random.geometric(p, size=None)

#Draw ten values from the geometric distribution, with the probability of an individual success equal to 0.3:

np.random.geometric(p=0.3, size=10)

array([3, 1, 1, 9, 1, 7, 1, 2, 1, 6])

In [31]:
# from numpy import random

# np.random.poisson(lam=1.0, size=None)

#example: draw a sample of poisson random variables with λ=5, size = 500. Display a histogram of the sample.

np.random.poisson(5, 20)

# import matplotlib.pyplot as plt

# count, bins, ignored = plt.hist(s, 14, density=True)
# plt.show()

array([5, 6, 6, 3, 9, 2, 5, 6, 5, 0, 6, 6, 6, 5, 6, 8, 4, 5, 4, 2])

In [28]:
from numpy import random
# np.random.uniform(low=0.0, high=1.0, size=None)

#example: generate a 5X2 matrix with the values of the vectors are between 0 and 1.

np.random.uniform(0.0, 1.0, size = (5,2))

array([[0.85579158, 0.92836813],
       [0.04551638, 0.87683327],
       [0.82121348, 0.47738449],
       [0.74072852, 0.49908354],
       [0.8319029 , 0.37512834]])

In [40]:
import numpy as np
quantile = np.arange (0.01, 1, 0.1)
   
# Random Variates

from scipy.stats import erlang
R = erlang.rvs(a, scale = 2,  size = 10)
print ("Random Variates : \n", R)

NameError: name 'a' is not defined

In [39]:
np.random.triangular(-5, 0, 5, 30)

array([-2.25631129, -0.22543387, -0.98729561,  0.89223229,  0.101949  ,
        1.80172198, -4.23302647,  1.4538379 ,  0.4269142 , -3.09030751,
        0.69488861,  4.42860228, -1.20539004, -1.7300038 , -0.40113604,
        2.74335322, -0.64933984,  1.56717144, -0.26733617, -2.68407694,
        1.07806457,  3.53224179,  0.53899215, -2.72005853,  2.98766588,
        1.16438291,  1.89468396,  0.40356427,  1.40376679,  1.88390749])